#FOR LOCAL DEVELOPMENT
services:
  db:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"
    environment:
    - ADMINER_DEFAULT_SERVER=localhost

  rabbitmq:
    ports:
      - "5672:5672" 
      - "15672:15672"




