#FOR LOCAL DEVELOPMENT
services:
  db:
    restart: "no"
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    environment:
    - ADMINER_DEFAULT_SERVER=db

  rabbitmq:
    ports:
      - "5672:5672" 
      - "15672:15672"
  
  # logging:
  #   build: ./logging
  #   environment:
  #     - ENVIRONMENT=dev
  #     - LOG_LEVEL=DEBUG
  
  userapi:
    environment:
      # - ENVIRONMENT=dev
      # - LOG_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ./user_api
        target: /app
  
  receiver:
    build: ./receiver
    # environment:
      # - ENVIRONMENT=dev
      # - LOG_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ./receiver
        target: /app
  
  # handler:
  #   build: ./handler
  #   environment:
  #     - ENVIRONMENT=dev
  #     - LOG_LEVEL=DEBUG
