services:
  logging:
    build: ./logging
    networks:
      - internal_network
    environment:
      - LOG_INFO_LOCAL_PATH=${LOG_INFO_LOCAL_PATH}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    volumes:
      - ./logs/:${LOG_INFO_LOCAL_PATH}

  rabbitmq:
    image: rabbitmq:3.13-management
    networks:
      - internal_network
    ports:
      - "5672:5672" # Todo: Remove this line
      - "15672:15672" # Todo: Remove this line
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  internal_network:
    driver: bridge




