version: '3.8'

services:
  logging:
    ports:
      - "8080:80"
    environment:
      - LOG_INFO_LOCAL_PATH=${LOG_INFO_LOCAL_PATH}
  rabbitmq:
    ports:
      - "5672:5672" 
      - "15672:15672"
