#FOR LOCAL DEVELOPMENT
services:
  db:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    environment:
    - ADMINER_DEFAULT_SERVER=db

  rabbitmq:
    ports:
      - "5672:5672" 
      - "15672:15672"
  
  userapi:
    environment:
      - ENV=dev
      - LOG_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ./user_api
        target: /app



