name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml


  # # Deploy to staging
  # deploy:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   steps:
  #     - name: Test
  #       run: echo "Testing..."

  #     - name: Configure SSH
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SSH_HOST: ${{ secrets.SSH_HOST }}
  #         SSH_USER: ${{ secrets.SSH_USER }}
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
  #         chmod 600 ~/.ssh/github
  #         echo "SSH_HOST: '$SSH_HOST'"
  #         echo "SSH_USER: '$SSH_USER'"
  #         cat >> ~/.ssh/config << END
  #         Host Target
  #           HostName $SSH_HOST
  #           User $SSH_USER
  #           IdentityFile ~/.ssh/github
  #           LogLevel ERROR
  #           StrictHostKeyChecking no
  #         END

  #     - name: Create env file
  #       id: create-env
  #       env:
  #         # General
  #         ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  #         ### Logs:
  #         LOG_LEVEL: ${{ vars.LOG_LEVEL }}
  #         LOGGING_EXCHANGE: ${{ vars.LOGGING_EXCHANGE }}
  #         LOG_QUEUE: ${{ vars.LOG_QUEUE }}
  #         RECEIVER_ID: ${{ vars.RECEIVER_ID }}
  #         HANDLER_ID: ${{ vars.HANDLER_ID }}
  #         USERAPI_ID: ${{ vars.USERAPI_ID }}
  #         ### Queue:
  #         RABBITMQ_DNS: ${{ vars.RABBITMQ_DNS }}
  #         RABBITMQ_PORT: ${{ vars.RABBITMQ_PORT }}
  #         RABBITMQ_USER: ${{ vars.RABBITMQ_USER }}
  #         RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

  #         #Logging
  #         LOG_INFO_LOCAL_PATH: ${{ vars.LOG_INFO_LOCAL_PATH }}
  #         LOG_FILE_MAX_SIZE: ${{ vars.LOG_FILE_MAX_SIZE }}
  #         LOG_FILE_BACKUP_COUNT: ${{ vars.LOG_FILE_BACKUP_COUNT }}
  #         REMOTE_LOG_LEVEL: ${{ vars.REMOTE_LOG_LEVEL }}
  #         REMOTE_LOG_ADDRESS: ${{ vars.REMOTE_LOG_ADDRESS }}
  #         REMOTE_LOG_PORT: ${{ vars.REMOTE_LOG_PORT }}
  #         # Receiver
  #         # ...
  #         # Handler
  #         # ...
  #         # Userapi
  #         USERS_OPEN_REGISTRATION: ${{ vars.USERS_OPEN_REGISTRATION }}
  #         INSERT_EXAMPLE_DATA: ${{ vars.INSERT_EXAMPLE_DATA }}
  #         SMTP_PORT: ${{ vars.SMTP_PORT }}
  #         SMTP_HOST: ${{ vars.SMTP_HOST }}
  #         SMTP_USER: ${{ vars.SMTP_USER }}
  #         SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  #         EMAILS_FROM_EMAIL: ${{ vars.EMAILS_FROM_EMAIL }}
  #         EMAILS_FROM_NAME: ${{ vars.EMAILS_FROM_NAME }}

  #         # Receiver | Handler
  #         HANDLER_EXCHANGE: ${{ vars.HANDLER_EXCHANGE }}
  #         MESSAGES_QUEUE: ${{ vars.MESSAGES_QUEUE }}

  #         # Userapi | Receiver
  #         RECEIVER_API_V1_STR: ${{ vars.RECEIVER_API_V1_STR }}
  #         USERAPI_API_V1_STR: ${{ vars.USERAPI_API_V1_STR }}
  #         SECRET_KEY: ${{ secrets.SECRET_KEY }}
  #         PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  #         DOMAIN: ${{ vars.DOMAIN }}

  #         # Userapi | Handler
  #         RPC_QUEUE: ${{ vars.RPC_QUEUE }}
  #         ### Superuser
  #         FIRST_SUPERUSER_EMAIL: ${{ vars.FIRST_SUPERUSER_EMAIL }}
  #         FIRST_SUPERUSERNAME: ${{ vars.FIRST_SUPERUSERNAME }}
  #         FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
  #         ### DB
  #         POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  #         POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  #         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  #         POSTGRES_DB: ${{ vars.POSTGRES_DB }}

  #       run: |
  #         echo ENVIRONMENT=$ENVIRONMENT >> .env

  #         echo LOG_LEVEL=$LOG_LEVEL >> .env
  #         echo LOGGING_EXCHANGE=$LOGGING_EXCHANGE >> .env
  #         echo LOG_QUEUE=$LOG_QUEUE >> .env
  #         echo RECEIVER_ID=$RECEIVER_ID >> .env
  #         echo HANDLER_ID=$HANDLER_ID >> .env
  #         echo USERAPI_ID=$USERAPI_ID >> .env

  #         echo RABBITMQ_DNS=$RABBITMQ_DNS >> .env
  #         echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
  #         echo RABBITMQ_USER=$RABBITMQ_USER >> .env
  #         echo RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD >> .env

  #         echo LOG_INFO_LOCAL_PATH=$LOG_INFO_LOCAL_PATH >> .env
  #         echo LOG_FILE_MAX_SIZE=$LOG_FILE_MAX_SIZE >> .env
  #         echo LOG_FILE_BACKUP_COUNT=$LOG_FILE_BACKUP_COUNT >> .env
  #         echo REMOTE_LOG_LEVEL=$REMOTE_LOG_LEVEL >> .env
  #         echo REMOTE_LOG_ADDRESS=$REMOTE_LOG_ADDRESS >> .env
  #         echo REMOTE_LOG_PORT=$REMOTE_LOG_PORT >> .env
          
  #         echo USERS_OPEN_REGISTRATION=$USERS_OPEN_REGISTRATION >> .env
  #         echo INSERT_EXAMPLE_DATA=$INSERT_EXAMPLE_DATA >> .env
  #         echo SMTP_PORT=$SMTP_PORT >> .env
  #         echo SMTP_HOST=$SMTP_HOST >> .env
  #         echo SMTP_USER=$SMTP_USER >> .env
  #         echo SMTP_PASSWORD=$SMTP_PASSWORD >> .env
  #         echo EMAILS_FROM_EMAIL=$EMAILS_FROM_EMAIL >> .env
  #         echo EMAILS_FROM_NAME=$EMAILS_FROM_NAME >> .env

  #         echo RECEIVER_API_V1_STR=$RECEIVER_API_V1_STR >> .env
  #         echo USERAPI_API_V1_STR=$USERAPI_API_V1_STR >> .env
  #         echo HANDLER_EXCHANGE=$HANDLER_EXCHANGE >> .env
  #         echo MESSAGES_QUEUE=$MESSAGES_QUEUE >> .env

  #         echo SECRET_KEY=$SECRET_KEY >> .env
  #         echo PROJECT_NAME=$PROJECT_NAME >> .env
  #         echo DOMAIN=$DOMAIN >> .env

  #         echo RPC_QUEUE=$RPC_QUEUE >> .env

  #         echo FIRST_SUPERUSER_EMAIL=$FIRST_SUPERUSER_EMAIL >> .env
  #         echo FIRST_SUPERUSERNAME=$FIRST_SUPERUSERNAME >> .env
  #         echo FIRST_SUPERUSER_PASSWORD=$FIRST_SUPERUSER_PASSWORD >> .env
          
  #         echo POSTGRES_PORT=$POSTGRES_PORT >> .env
  #         echo POSTGRES_USER=$POSTGRES_USER >> .env
  #         echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
  #         echo POSTGRES_DB=$POSTGRES_DB >> .env

  #     - name: Pull repository
  #       run: |
  #         ssh Target "cd iot_server && git pull origin main"

  #     - name: Send env file
  #       run: |
  #         scp .env Target:iot_server/.env

  #     - name: Deploy
  #       if: steps.create-env.outcome == 'success'
  #       run: |
  #           ssh Target "cd iot_server && make compose-down && make compose-prod"
      
  #     - name: Clean up
  #       run: |
  #         rm .env
  #         # ssh Target "rm iot_server/.env"
  #         ssh Target "docker image prune -f"
          
