name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  # test:
  #   name: Tests
  #   uses: ./.github/workflows/test.yml
    
  # quality-assurance:
  #   name: Quality Assurance
  #   uses: ./.github/workflows/qa.yml

  deploy:
    name: Deploy
    # needs: [test, quality-assurance]
    uses: ./.github/workflows/deploy-staging.yml



    
