name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint flake8
        run: |
          echo "Running linteron Logging"
          flake8 logging/ --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 logging/ --count --select=E9,F63,F7,F82 --show-source --statistics

          # --exit-zero 

          echo "Running linter on UserAPI"
          flake8 user_api/ --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 user_api/ --count --select=E9,F63,F7,F82 --show-source --statistics
