name: Test
on: [pull_request, workflow_call]

jobs:
  tests-logging:
    name: Tests Logging Service
    uses: ./.github/workflows/test_logging.yml
  
  tests-userapi:
    name: Tests User API Service
    uses: ./.github/workflows/test_userapi.yml
  
  tests-receiver:
    name: Tests Receiver Service
    uses: ./.github/workflows/test_receiver.yml
  
  tests-handler:
    name: Tests Handler Service  # Need to be made after the userapi wich is the responsible for migrations
    uses: ./.github/workflows/test_handler.yml
    

  # # https://github.com/marketplace/actions/alls-green#why
  # alls-green:  # This job does nothing and is only used for the branch protection
  #   if: always()
  #   needs:
  #     - test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Decide whether the needed jobs succeeded or failed
  #       uses: re-actors/alls-green@release/v1
  #       with:
  #         jobs: ${{ toJSON(needs) }}
