name: Test Logging
on: [workflow_call]

jobs:
  logging-tests:
    runs-on: ubuntu-latest
    environment: Test
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}

      LOG_EXCHANGE: ${{ vars.LOG_EXCHANGE }}
      LOG_QUEUE: ${{ vars.LOG_QUEUE }}
      RECEIVER_ID: ${{ vars.RECEIVER_ID }}
      HANDLER_ID: ${{ vars.HANDLER_ID }}
      USERAPI_ID: ${{ vars.USERAPI_ID }}

      RABBITMQ_DNS: ${{ vars.RABBITMQ_DNS }}

      LOG_INFO_LOCAL_PATH: ${{ vars.LOG_INFO_LOCAL_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        id: create-env
        run: |
          echo ENVIRONMENT=$ENVIRONMENT >> .env
          echo LOG_LEVEL=$LOG_LEVEL >> .env
          echo LOG_EXCHANGE=$LOG_EXCHANGE >> .env
          echo LOG_QUEUE=$LOG_QUEUE >> .env
          echo RECEIVER_ID=$RECEIVER_ID >> .env
          echo HANDLER_ID=$HANDLER_ID >> .env
          echo USERAPI_ID=$USERAPI_ID >> .env
          echo RABBITMQ_DNS=$RABBITMQ_DNS >> .env
          echo LOG_INFO_LOCAL_PATH=$LOG_INFO_LOCAL_PATH >> .env

      - name: Tests - Logging service
        run: |
          make compose-dev-d s="rabbitmq logging"
          docker compose exec -T logging bash tests-start.sh

      # Cleanup
      - name: Cleanup
        run: |
          make compose-down-dev
