name: Test Handler
on: [workflow_call]

jobs:
  handler-tests:
    runs-on: ubuntu-latest
    environment: Test
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}

      LOG_EXCHANGE: ${{ vars.LOG_EXCHANGE }}
      LOG_QUEUE: ${{ vars.LOG_QUEUE }}
      HANDLER_ID: ${{ vars.HANDLER_ID }}

      RABBITMQ_DNS: ${{ vars.RABBITMQ_DNS }}

      MESSAGES_EXCHANGE: ${{ vars.MESSAGES_EXCHANGE }}
      MESSAGES_QUEUE: ${{ vars.MESSAGES_EXCHANGE }}

      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}

      LOG_INFO_LOCAL_PATH: ${{ vars.LOG_INFO_LOCAL_PATH }} # Need to add this so compose wont fail to bind volume

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        id: create-env
        run: |
          echo ENVIRONMENT=$ENVIRONMENT >> .env
          echo LOG_LEVEL=$LOG_LEVEL >> .env
          echo LOG_EXCHANGE=$LOG_EXCHANGE >> .env
          echo LOG_QUEUE=$LOG_QUEUE >> .env
          echo RECEIVER_ID=$RECEIVER_ID >> .env
          echo RABBITMQ_DNS=$RABBITMQ_DNS >> .env
          echo MESSAGES_EXCHANGE=$MESSAGES_EXCHANGE >> .env
          echo MESSAGES_QUEUE=$MESSAGES_QUEUE >> .env
          echo POSTGRES_PORT=$POSTGRES_PORT >> .env
          echo POSTGRES_USER=$POSTGRES_USER >> .env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
          echo POSTGRES_DB=$POSTGRES_DB >> .env
          echo LOG_INFO_LOCAL_PATH=$LOG_INFO_LOCAL_PATH >> .env

      - name: Tests - Hanlder service
        run: |
          make compose-dev-d s="rabbitmq handler"
          docker compose exec -T handler bash tests-start.sh

      # Cleanup
      - name: Cleanup
        run: |
          make compose-down-dev

