name: Test Receiver
on: [workflow_call]

jobs:
  receiver-tests:
    runs-on: ubuntu-latest
    environment: Test
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}

      LOG_EXCHANGE: ${{ vars.LOG_EXCHANGE }}
      LOG_QUEUE: ${{ vars.LOG_QUEUE }}
      RECEIVER_ID: ${{ vars.RECEIVER_ID }}

      RABBITMQ_DNS: ${{ vars.RABBITMQ_DNS }}

      MESSAGES_EXCHANGE: ${{ vars.MESSAGES_EXCHANGE }}
      MESSAGES_QUEUE: ${{ vars.MESSAGES_EXCHANGE }}

      LOG_INFO_LOCAL_PATH: ${{ vars.LOG_INFO_LOCAL_PATH }} # Need to add this so compose wont fail to bind volume

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        id: create-env
        run: |
          echo ENVIRONMENT=$ENVIRONMENT >> .env
          echo LOG_LEVEL=$LOG_LEVEL >> .env
          echo LOG_EXCHANGE=$LOG_EXCHANGE >> .env
          echo LOG_QUEUE=$LOG_QUEUE >> .env
          echo RECEIVER_ID=$RECEIVER_ID >> .env
          echo RABBITMQ_DNS=$RABBITMQ_DNS >> .env
          echo MESSAGES_EXCHANGE=$MESSAGES_EXCHANGE >> .env
          echo MESSAGES_QUEUE=$MESSAGES_QUEUE >> .env
          echo LOG_INFO_LOCAL_PATH=$LOG_INFO_LOCAL_PATH >> .env

      - name: Tests - Receiver service
        run: |
          make compose-dev-d s="rabbitmq receiver"
          docker compose exec -T receiver bash tests-start.sh

      # Cleanup
      - name: Cleanup
        run: |
          make compose-down-dev

